### ISSUE TITLE
0.8.0 Feature List

### ISSUE THREAD

**Issue by ibraheemdev** [ibraheemdev/matchit#35]
- [x] Remove trailing slash functionality (https://github.com/ibraheemdev/matchit/issues/31#issuecomment-1588148126)
- [x] Switch to `{x}` syntax for route parameters (https://github.com/ibraheemdev/matchit/issues/23#issuecomment-1272107900, https://github.com/ibraheemdev/matchit/issues/17#issuecomment-1112830972)
- [x] Implement route normalization (https://github.com/ibraheemdev/matchit/issues/13).

**Comment by jplatte** [comment]
I think I read a discussion about the new syntax before, this includes escaping `{` and `}` with `{{` and `}}` just like in Rust's `format!` strings, right?

**Comment by ibraheemdev** [comment]
@jplatte yes. Catch-all routes will also be specified within the `{` `}` as `/foo/{*wildcard}`.

**Comment by ibraheemdev** [comment]
With `{}` parameters, we also run into more interesting conflicts. For example, given `/{foo}.{bar}` and `/{foo}b{bar}`, what does `/ab.cd` match? Both are `/{ab}.{cd}` and `{a}b{.cd}` are matches, but without a user-given priority the choice is unclear, so the routes should be considered conflicting.

There are two rules that I can see working for conflicts:
1. Only allow a single specialized pattern per route segment. e.g. `/{foo}` and `/{foo}.{bar}` is fine, but adding `/{foo}b{bar}` causes a conflict.
2. Allow multiple specialized patterns as long as they contain a different number of parameters. e.g. `/{foo}`, `/{foo}.{bar}`, `/{foo}.{bar}.{baz}` are fine, but adding `/{foo}-{bar}` causes a conflict. Specializations with a larger number of parameters take priority, e.g. `/foo.bar.baz` matches `/{foo}.{bar}.{baz}`, not `/{foo}.{bar.baz}`.

I'm leaning towards option 1 for simplicity's sake, and I'm not sure how much value option 2 would add.

**Comment by jplatte** [comment]
Hey @ibraheemdev, could you use any help with this? Looks like [we'll want to ship axum 0.8 sooner rather than later](https://github.com/tokio-rs/axum/pull/2468#issuecomment-1872583692) (maybe around end of Q1'24, but that's entirely my personal guess) and it would be great to have the new matchit with different routing syntax included.

**Comment by ibraheemdev** [comment]
@jplatte Thanks for the reminder. I have most of the work finished locally, just need to clean some things up. It should be done by then, if not I'll try to have a 0.8 release with the new syntax that's still restricted to the old conflict rules.

**Comment by Totodore** [comment]
Hey @ibraheemdev, #49 will be part of this version? Or do you plan to release it later? It is a feature that I would really need for my lib [socketioxide](https://github.com/totodore/socketioxide).

**Comment by ibraheemdev** [comment]
0.8 has been released! See the [release notes](https://github.com/ibraheemdev/matchit/releases/tag/v0.8.0) for details.

@Totodore we can get #49 merged with a minor version bump now once it's ready that the major changes are out of the way.
